DROP TABLE IF EXISTS promocodes;
DROP TABLE IF EXISTS users;

CREATE TABLE users (id BIGSERIAL PRIMARY KEY);
CREATE TABLE promocodes (id BIGSERIAL PRIMARY KEY, value VARCHAR(255), user_id BIGSERIAL, status VARCHAR(255), FOREIGN KEY (user_id) REFERENCES users (id));

INSERT INTO users VALUES (1);
INSERT INTO users VALUES (2);
INSERT INTO users VALUES (3);
