DROP TABLE IF EXISTS promocodes;
DROP TABLE IF EXISTS users;

CREATE TABLE users (id BIGSERIAL PRIMARY KEY);
CREATE TABLE promocodes (id BIGSERIAL PRIMARY KEY, value VARCHAR(255), user_id BIGSERIAL, FOREIGN KEY (user_id) REFERENCES users (id));